/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pro.GestaoFinanceira.view;

import br.pro.GestaoFinanceira.data.DespesasData;
import br.pro.GestaoFinanceira.data.EmpresaData;
import br.pro.GestaoFinanceira.model.DespesasModel;
import br.pro.GestaoFinanceira.model.EmpresaModel;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author heito
 */
public class JIFCadDespesas extends javax.swing.JInternalFrame {
    //objeto model 
    ArrayList<DespesasModel> lista;
    ArrayList<EmpresaModel> listaEmpresa;
    DespesasModel obj;
    EmpresaModel empresa;
    DespesasData DAO;
    EmpresaData DAOEmpresa;
    /**
     * Creates new form JIFCadFuncionario
     */
    public JIFCadDespesas() {
       
        //instanciação dos obj no construtor 
        try{
            
            lista = new ArrayList<>();
            listaEmpresa = new ArrayList<>();
            empresa = new EmpresaModel();
            obj = new DespesasModel();
            DAO = new DespesasData();
            DAOEmpresa = new EmpresaData();
            listaEmpresa = DAOEmpresa.carregarCombo();
            initComponents();
            for(EmpresaModel empresa : listaEmpresa){
                jcbEmpresa.addItem(""+empresa.getIdempresa());
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpEdicao = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlIddespesa = new javax.swing.JLabel();
        jlIddespesa1 = new javax.swing.JLabel();
        jlEmpresa = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jcbEmpresa = new javax.swing.JComboBox<>();
        jlDatadespesa = new javax.swing.JLabel();
        jlValordespesa = new javax.swing.JLabel();
        jtValordespesa = new javax.swing.JTextField();
        jlDetalhamentodespesa = new javax.swing.JLabel();
        jtDetalhamentodespesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtDatadespesa = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlPesquisa = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbSalvar1 = new javax.swing.JButton();
        jlDatadespesa1 = new javax.swing.JLabel();
        jtDetalhamentodespesa1 = new javax.swing.JTextField();
        jlDetalhamentodespesa1 = new javax.swing.JLabel();
        jlValordespesa1 = new javax.swing.JLabel();
        jtValordespesa1 = new javax.swing.JTextField();
        jbCancelar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbDados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbPesquisar = new javax.swing.JButton();
        jtDatadespesa1 = new javax.swing.JFormattedTextField();
        jtPesquisa = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro/Edição de Despesas");
        setEnabled(false);

        jPanel1.setLayout(null);

        jlIddespesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIddespesa.setText("*ID:");
        jPanel1.add(jlIddespesa);
        jlIddespesa.setBounds(10, 51, 100, 30);

        jlIddespesa1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jlIddespesa1);
        jlIddespesa1.setBounds(116, 51, 237, 30);

        jlEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEmpresa.setText("Empresa:");
        jPanel1.add(jlEmpresa);
        jlEmpresa.setBounds(10, 243, 100, 30);

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbNovoIcon.png"))); // NOI18N
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jbNovo);
        jbNovo.setBounds(10, 291, 50, 40);

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbSalvarIcon.png"))); // NOI18N
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalvar);
        jbSalvar.setBounds(130, 291, 50, 40);

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbCancelarIcon.png"))); // NOI18N
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar);
        jbCancelar.setBounds(70, 291, 50, 40);

        jPanel1.add(jcbEmpresa);
        jcbEmpresa.setBounds(114, 243, 237, 30);

        jlDatadespesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDatadespesa.setText("*Data:");
        jPanel1.add(jlDatadespesa);
        jlDatadespesa.setBounds(10, 99, 100, 30);

        jlValordespesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlValordespesa.setText("*Valor:");
        jPanel1.add(jlValordespesa);
        jlValordespesa.setBounds(12, 147, 100, 30);

        jtValordespesa.setEnabled(false);
        jPanel1.add(jtValordespesa);
        jtValordespesa.setBounds(116, 147, 237, 30);

        jlDetalhamentodespesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDetalhamentodespesa.setText("*Detalhamento:");
        jPanel1.add(jlDetalhamentodespesa);
        jlDetalhamentodespesa.setBounds(10, 195, 100, 30);

        jtDetalhamentodespesa.setEnabled(false);
        jPanel1.add(jtDetalhamentodespesa);
        jtDetalhamentodespesa.setBounds(114, 195, 237, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO DESPESA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 920, 33);

        try {
            jtDatadespesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDatadespesa.setEnabled(false);
        jPanel1.add(jtDatadespesa);
        jtDatadespesa.setBounds(114, 99, 237, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/JIFCadDespesasIcon.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 30, 520, 520);

        jtpEdicao.addTab("Cadastro", jPanel1);

        jlPesquisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPesquisa.setText("Pesquisa:");

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbEditarIcon.png"))); // NOI18N
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbExcluirIcon.png"))); // NOI18N
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbSalvarIcon.png"))); // NOI18N
        jbSalvar1.setEnabled(false);
        jbSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvar1ActionPerformed(evt);
            }
        });

        jlDatadespesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDatadespesa1.setText("*Data:");

        jtDetalhamentodespesa1.setEnabled(false);

        jlDetalhamentodespesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDetalhamentodespesa1.setText("*Detalhamento:");

        jlValordespesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlValordespesa1.setText("*Valor:");

        jtValordespesa1.setEnabled(false);

        jbCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbCancelarIcon.png"))); // NOI18N
        jbCancelar1.setEnabled(false);
        jbCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar1ActionPerformed(evt);
            }
        });

        jtbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Valor", "Data", "Detalhamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbDados);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pesquise a data para realizar Alteração/Exclusão de DESPESAS");

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbPesquisaIcon.png"))); // NOI18N
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        try {
            jtDatadespesa1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDatadespesa1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlValordespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDatadespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtValordespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(jlDetalhamentodespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtDetalhamentodespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(103, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtDatadespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDetalhamentodespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtValordespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlValordespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDetalhamentodespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDatadespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDatadespesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jtpEdicao.addTab("Edição", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpEdicao, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jtpEdicao)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjeto()){
                    if(DAO.incluir(obj)){
                        JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso", "Salvar", JOptionPane.WARNING_MESSAGE);
                        jbCancelarActionPerformed(evt);
                    }else{
                        JOptionPane.showMessageDialog(this, "Erro ao salvar: ", "Salvar-Despesa", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }    
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Salvar-Despesa", JOptionPane.ERROR_MESSAGE);   
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        //chamando metodos da classe formularios
        br.pro.GestaoEmpresarial.extras.Formularios.limparCampos(this);
        br.pro.GestaoEmpresarial.extras.Formularios.tratarCampos(this, true);
        br.pro.GestaoEmpresarial.extras.Formularios.limparTabela(jtbDados);
        //configurando os botões
        jlIddespesa1.setText("0");
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jtpEdicao.setEnabled(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        br.pro.GestaoEmpresarial.extras.Formularios.limparCampos(this);
        br.pro.GestaoEmpresarial.extras.Formularios.tratarCampos(this, false);
        br.pro.GestaoEmpresarial.extras.Formularios.limparTabela(jtbDados);
        jlIddespesa1.setText("0");
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);        
        jbCancelar.setEnabled(false);
        jtPesquisa.setEnabled(true);
        jbPesquisar.setEnabled(true);
        jtpEdicao.setEnabled(true);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        br.pro.GestaoEmpresarial.extras.Formularios.tratarCampos(this, true);
        jcbEmpresa.setEnabled(false);
        jbSalvar1.setEnabled(true);
        jbCancelar1.setEnabled(true);
        jbExcluir.setEnabled(false);
        jbEditar.setEnabled(false);
        jbPesquisar.setEnabled(false);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this ,"Você tem certeza que deseja Excluir a Despesa ("+jlIddespesa1.getText()+")", "Exclusão",JOptionPane.YES_NO_OPTION);
        if (resposta == 0) {
            try {
                if(DAO.excluir(Integer.parseInt(jlIddespesa1.getText()))){
                    JOptionPane.showMessageDialog(this, "Excluído com sucesso");
                    jbCancelar1ActionPerformed(evt);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o registro: "+e.getMessage());
            }
        }else{  
            JOptionPane.showMessageDialog(this, "o registro não será excluído");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDadosMouseClicked
         try {
            int linha = jtbDados.getSelectedRow();
            if(linha>-1){
                jlIddespesa1.setText(jtbDados.getValueAt(linha, 0).toString());
                jtValordespesa1.setText(jtbDados.getValueAt(linha, 1).toString());
                jtDatadespesa1.setText(jtbDados.getValueAt(linha,2).toString());
                jtDetalhamentodespesa1.setText(jtbDados.getValueAt(linha,3).toString());
                
                for(int i=0;i<listaEmpresa.size();i++){
                    if(listaEmpresa.get(i).getIdempresa() == lista.get(linha).getEmpresa().getIdempresa()){
                        jcbEmpresa.setSelectedIndex(i);
                    }
                }
                
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jbCancelar1.setEnabled(true);
                jbPesquisar.setEnabled(false);
                jtpEdicao.setEnabled(false);
            } else {
                jbEditar.setEnabled(false);
                jbExcluir.setEnabled(false);
                jbCancelar1.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar o registro: "+e.getMessage());
        }

    }//GEN-LAST:event_jtbDadosMouseClicked

    private void jbSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvar1ActionPerformed
        try{
        if(validarCampos1()){
            if(atualizarObjeto()){    
                if(DAO.editar(obj)){
                    JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso", "Atualizar", JOptionPane.WARNING_MESSAGE);
                    jbCancelar1ActionPerformed(evt);
                } 
                else {
                    JOptionPane.showMessageDialog(this, "Erro ao Atualizar: ", "Atualizar-Despesa", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), "Atualizar-Despesa", JOptionPane.ERROR_MESSAGE);       
    }
    }//GEN-LAST:event_jbSalvar1ActionPerformed

    private void jbCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar1ActionPerformed
        br.pro.GestaoEmpresarial.extras.Formularios.limparCampos(this);
        br.pro.GestaoEmpresarial.extras.Formularios.tratarCampos(this, false);
        br.pro.GestaoEmpresarial.extras.Formularios.limparTabela(jtbDados);
        jbSalvar1.setEnabled(false);
        jbCancelar1.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtPesquisa.setText("");
        jbPesquisar.setEnabled(true);
        jtPesquisa.setEnabled(true);
        jtpEdicao.setEnabled(true);
    }//GEN-LAST:event_jbCancelar1ActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
    try {
        lista = DAO.pesquisar(jtPesquisa.getText());
        DefaultTableModel mp = (DefaultTableModel) jtbDados.getModel();
        mp.setNumRows(0);
        for(DespesasModel ob: lista){
            mp.addRow(new String[]{""+ob.getIddespesa(),""+ob.getValordespesa(),""+ob.getDatadespesa(),ob.getDetalhamentodespesa()});
        }
        jbPesquisar.setEnabled(false);
        jbCancelar1.setEnabled(true);
    } catch (Exception e) {
       //JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+e.getMessage());
       e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jbPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelar1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbSalvar1;
    private javax.swing.JComboBox<String> jcbEmpresa;
    private javax.swing.JLabel jlDatadespesa;
    private javax.swing.JLabel jlDatadespesa1;
    private javax.swing.JLabel jlDetalhamentodespesa;
    private javax.swing.JLabel jlDetalhamentodespesa1;
    private javax.swing.JLabel jlEmpresa;
    private javax.swing.JLabel jlIddespesa;
    private javax.swing.JLabel jlIddespesa1;
    private javax.swing.JLabel jlPesquisa;
    private javax.swing.JLabel jlValordespesa;
    private javax.swing.JLabel jlValordespesa1;
    private javax.swing.JFormattedTextField jtDatadespesa;
    private javax.swing.JFormattedTextField jtDatadespesa1;
    private javax.swing.JTextField jtDetalhamentodespesa;
    private javax.swing.JTextField jtDetalhamentodespesa1;
    private javax.swing.JFormattedTextField jtPesquisa;
    private javax.swing.JTextField jtValordespesa;
    private javax.swing.JTextField jtValordespesa1;
    private javax.swing.JTable jtbDados;
    private javax.swing.JTabbedPane jtpEdicao;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos(){
        if(jtDatadespesa.getText().trim().length()<7 ){
            JOptionPane.showMessageDialog(null, "Caractere data Insuficiente(<7)", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jtValordespesa.getText().trim().length()<1 ){
            JOptionPane.showMessageDialog(null, "Caractere valor Insuficiente(<1)", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jtDetalhamentodespesa.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Detalhamento Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private boolean validarCampos1() throws Exception{
        if(jtDatadespesa1.getText().trim().length()<7){
            JOptionPane.showMessageDialog(null, "Caractere data Insuficiente(<7)", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jtValordespesa1.getText().trim().length()<1 ){
            JOptionPane.showMessageDialog(null, "Caractere valor Insuficiente(<1)", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jtDetalhamentodespesa1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Detalhamento Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private boolean preencherObjeto() throws Exception{
        obj.setIddespesa(Integer.parseInt(jlIddespesa1.getText()));
        obj.setDatadespesa(jtDatadespesa.getText());
        obj.setValordespesa(Float.parseFloat(jtValordespesa.getText()));
        obj.setDetalhamentodespesa(jtDetalhamentodespesa.getText());
        obj.setEmpresa(listaEmpresa.get(jcbEmpresa.getSelectedIndex()));
        
    return true;    
    }
    private boolean atualizarObjeto() throws Exception{
        obj.setIddespesa(Integer.parseInt(jlIddespesa1.getText()));
        obj.setDatadespesa(jtDatadespesa1.getText());
        obj.setValordespesa(Float.parseFloat(jtValordespesa1.getText()));
        obj.setDetalhamentodespesa(jtDetalhamentodespesa1.getText());
        obj.setEmpresa(listaEmpresa.get(jcbEmpresa.getSelectedIndex()));
        
    return true;    
    }
    
    private void formatarCampos() throws Exception{
        MaskFormatter maskdata = new MaskFormatter("##-##-####");
        maskdata.install(jtDatadespesa);
        maskdata.install(jtDatadespesa1);
        maskdata.install(jtPesquisa);
    }
    
}
