/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pro.GestaoFinanceira.view;

import br.pro.GestaoFinanceira.data.ClienteData;
import br.pro.GestaoFinanceira.data.EmpresaData;
import br.pro.GestaoFinanceira.model.ClienteModel;
import br.pro.GestaoFinanceira.model.EmpresaModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heito
 */
public class JIFCadCliente extends javax.swing.JInternalFrame {
    
    ArrayList<ClienteModel> lista;    
    ClienteModel obj;
    ClienteData DAO;
    EmpresaModel empresa;
    EmpresaData DAOEmpresa;
    ArrayList<EmpresaModel> listaEmpresa;
    //int acao=0;
    /**
     * Creates new form JIFCadFuncionario
     */
    public JIFCadCliente() {
        
        try{
            lista = new ArrayList<>();
            listaEmpresa = new ArrayList<>();
            obj = new ClienteModel();
            empresa = new EmpresaModel();
            DAO = new ClienteData();
            DAOEmpresa = new EmpresaData();
            listaEmpresa = DAOEmpresa.carregarCombo();
            initComponents();
            for(EmpresaModel e : listaEmpresa){
                jcbEmpresa.addItem(""+e.getIdempresa());
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro"+e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlIdcliente = new javax.swing.JLabel();
        jlContatocliente = new javax.swing.JLabel();
        jlNomecliente = new javax.swing.JLabel();
        jtContatocliente = new javax.swing.JTextField();
        jtNomecliente = new javax.swing.JTextField();
        jlCidadecliente = new javax.swing.JLabel();
        jtCidadecliente = new javax.swing.JTextField();
        jlIdcliente1 = new javax.swing.JLabel();
        jlRuacliente = new javax.swing.JLabel();
        jtRuacliente = new javax.swing.JTextField();
        jlCpfcliente = new javax.swing.JLabel();
        jtEmailcliente = new javax.swing.JTextField();
        jtCpfcliente = new javax.swing.JTextField();
        jlEmailcliente = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jlNumcasacliente = new javax.swing.JLabel();
        jtNumcasacliente = new javax.swing.JTextField();
        jlComplcasacliente = new javax.swing.JLabel();
        jtComplcasacliente = new javax.swing.JTextField();
        jlDadospessoais = new javax.swing.JLabel();
        jlLocalizacao = new javax.swing.JLabel();
        jlDatanasccliente = new javax.swing.JLabel();
        jtDatanasccliente = new javax.swing.JTextField();
        jlEmpresa = new javax.swing.JLabel();
        jcbEmpresa = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDados = new javax.swing.JTable();
        jlPesquisa = new javax.swing.JLabel();
        jtPesquisa = new javax.swing.JTextField();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbSalvar1 = new javax.swing.JButton();
        jlNomecliente1 = new javax.swing.JLabel();
        jtNomecliente1 = new javax.swing.JTextField();
        jlDatanasccliente1 = new javax.swing.JLabel();
        jtDatanasccliente1 = new javax.swing.JTextField();
        jlCpfcliente1 = new javax.swing.JLabel();
        jtCpfcliente1 = new javax.swing.JTextField();
        jtEmailcliente1 = new javax.swing.JTextField();
        jlEmailcliente1 = new javax.swing.JLabel();
        jlCidadecliente1 = new javax.swing.JLabel();
        jtCidadecliente1 = new javax.swing.JTextField();
        jlRuacliente1 = new javax.swing.JLabel();
        jtRuacliente1 = new javax.swing.JTextField();
        jlNumcasacliente1 = new javax.swing.JLabel();
        jtNumcasacliente1 = new javax.swing.JTextField();
        jlComplcasacliente1 = new javax.swing.JLabel();
        jtComplcasacliente1 = new javax.swing.JTextField();
        jtContatocliente1 = new javax.swing.JTextField();
        jlContatoCliente1 = new javax.swing.JLabel();
        jbCancelar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro/Edição de Cliente");
        setEnabled(false);

        jlIdcliente.setText("*ID Cliente:");

        jlContatocliente.setText("Telefone:");

        jlNomecliente.setText("*Nome Completo:");

        jtContatocliente.setEnabled(false);
        jtContatocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtContatoclienteActionPerformed(evt);
            }
        });

        jtNomecliente.setEnabled(false);
        jtNomecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeclienteActionPerformed(evt);
            }
        });

        jlCidadecliente.setText("Cidade Atual:");

        jtCidadecliente.setEnabled(false);
        jtCidadecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadeclienteActionPerformed(evt);
            }
        });

        jlIdcliente1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlIdcliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIdcliente1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlRuacliente.setText("Rua:");

        jtRuacliente.setEnabled(false);
        jtRuacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuaclienteActionPerformed(evt);
            }
        });

        jlCpfcliente.setText("*CPF:");

        jtEmailcliente.setEnabled(false);
        jtEmailcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailclienteActionPerformed(evt);
            }
        });

        jtCpfcliente.setEnabled(false);
        jtCpfcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCpfclienteActionPerformed(evt);
            }
        });

        jlEmailcliente.setText("Email:");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlNumcasacliente.setText("Número da Casa:");

        jtNumcasacliente.setEnabled(false);
        jtNumcasacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumcasaclienteActionPerformed(evt);
            }
        });

        jlComplcasacliente.setText("Complemento Endereço:");

        jtComplcasacliente.setEnabled(false);
        jtComplcasacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtComplcasaclienteActionPerformed(evt);
            }
        });

        jlDadospessoais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlDadospessoais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDadospessoais.setText("Dados Pessoais");

        jlLocalizacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlLocalizacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLocalizacao.setText("Localização");

        jlDatanasccliente.setText("*Data Nascimento:");

        jtDatanasccliente.setEnabled(false);
        jtDatanasccliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDatanascclienteActionPerformed(evt);
            }
        });

        jlEmpresa.setText("Empresa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jlDadospessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlIdcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlNomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jlIdcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtNomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlEmailcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEmailcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73)
                        .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlComplcasacliente)
                            .addComponent(jlNumcasacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlContatocliente)
                            .addComponent(jlRuacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCidadecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCidadecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRuacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtContatocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNumcasacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtComplcasacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlEmpresa)
                        .addGap(56, 56, 56)
                        .addComponent(jcbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlDatanasccliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDatanasccliente, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlCpfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCpfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlDadospessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlIdcliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addComponent(jlIdcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNovo)
                        .addComponent(jbCancelar)
                        .addComponent(jbSalvar)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDatanasccliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDatanasccliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCpfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCpfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtEmailcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEmailcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jlLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlCidadecliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtCidadecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRuacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtRuacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumcasacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNumcasacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlComplcasacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtComplcasacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlContatocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtContatocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jtbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDados);

        jlPesquisa.setText("Pesquisar:");

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSalvar1.setText("Salvar");
        jbSalvar1.setEnabled(false);
        jbSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvar1ActionPerformed(evt);
            }
        });

        jlNomecliente1.setText("*Nome Completo:");

        jtNomecliente1.setEnabled(false);
        jtNomecliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomecliente1ActionPerformed(evt);
            }
        });

        jlDatanasccliente1.setText("*Data Nascimento:");

        jtDatanasccliente1.setEnabled(false);
        jtDatanasccliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDatanasccliente1ActionPerformed(evt);
            }
        });

        jlCpfcliente1.setText("*CPF:");

        jtCpfcliente1.setEnabled(false);
        jtCpfcliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCpfcliente1ActionPerformed(evt);
            }
        });

        jtEmailcliente1.setEnabled(false);
        jtEmailcliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailcliente1ActionPerformed(evt);
            }
        });

        jlEmailcliente1.setText("Email:");

        jlCidadecliente1.setText("Cidade:");

        jtCidadecliente1.setEnabled(false);
        jtCidadecliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadecliente1ActionPerformed(evt);
            }
        });

        jlRuacliente1.setText("Rua:");

        jtRuacliente1.setEnabled(false);
        jtRuacliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuacliente1ActionPerformed(evt);
            }
        });

        jlNumcasacliente1.setText("Número da Casa:");

        jtNumcasacliente1.setEnabled(false);
        jtNumcasacliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumcasacliente1ActionPerformed(evt);
            }
        });

        jlComplcasacliente1.setText("Complemento Endereço:");

        jtComplcasacliente1.setEnabled(false);
        jtComplcasacliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtComplcasacliente1ActionPerformed(evt);
            }
        });

        jtContatocliente1.setEnabled(false);
        jtContatocliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtContatocliente1ActionPerformed(evt);
            }
        });

        jlContatoCliente1.setText("Telefone:");

        jbCancelar1.setText("Cancelar");
        jbCancelar1.setEnabled(false);
        jbCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Digite o CPF para realizar a Pesquisa/Alteração/Exclusão de Clientes ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlPesquisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jbSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlNomecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNomecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlCpfcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCpfcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlDatanasccliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtDatanasccliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEmailcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlContatoCliente1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtContatocliente1)
                                    .addComponent(jtEmailcliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlRuacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtRuacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlCidadecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCidadecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jlComplcasacliente1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtComplcasacliente1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jlNumcasacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtNumcasacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(110, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbEditar)
                        .addComponent(jbExcluir)
                        .addComponent(jbSalvar1)
                        .addComponent(jbCancelar1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlPesquisa)
                        .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCidadecliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtCidadecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRuacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRuacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNumcasacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNumcasacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlComplcasacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtComplcasacliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNomecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNomecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDatanasccliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDatanasccliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCpfcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCpfcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtEmailcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEmailcliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlContatoCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(57, 57, 57))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtContatocliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jTabbedPane1.addTab("Edição", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar1ActionPerformed
        br.pro.GestaoFinanceira.extras.Formularios.limparCampos(this);
        br.pro.GestaoFinanceira.extras.Formularios.tratarCampos(this, false);
        br.pro.GestaoFinanceira.extras.Formularios.limparTabela(jtbDados);
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbSalvar1.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbCancelar1.setEnabled(false);
        jbEditar.setEnabled(true);
        jbExcluir.setEnabled(false);
        jtPesquisa.setText("");
        jtPesquisa.setEnabled(true);
    }//GEN-LAST:event_jbCancelar1ActionPerformed

    private void jtContatocliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtContatocliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtContatocliente1ActionPerformed

    private void jtComplcasacliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtComplcasacliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtComplcasacliente1ActionPerformed

    private void jtNumcasacliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumcasacliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumcasacliente1ActionPerformed

    private void jtRuacliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuacliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRuacliente1ActionPerformed

    private void jtCidadecliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadecliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadecliente1ActionPerformed

    private void jtEmailcliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailcliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailcliente1ActionPerformed

    private void jtCpfcliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCpfcliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCpfcliente1ActionPerformed

    private void jtDatanasccliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDatanasccliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDatanasccliente1ActionPerformed

    private void jtNomecliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomecliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomecliente1ActionPerformed

    private void jbSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvar1ActionPerformed
        try{
            if(validarCampos()){
                if(atualizarObjeto()){
                    if(DAO.editar(obj)){
                        JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso", "Atualizar", JOptionPane.WARNING_MESSAGE);
                        jbCancelarActionPerformed(evt);
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Erro ao Atualizar: ", "Atualizar-Cliente", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), "Atualizar-Cliente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvar1ActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this ,"Você tem certeza que deseja Excluir o Cliente ("+jtNomecliente.getText()+")", "Exclusão",JOptionPane.YES_NO_OPTION);
        if (resposta == 0) {
            try {
                if(DAO.excluir(Integer.parseInt(jlIdcliente1.getText()))){
                    JOptionPane.showMessageDialog(this, "Excluído com sucesso");
                    jbCancelarActionPerformed(evt);
                    jtPesquisa.setEnabled(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o registro: "+e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "O registro não será excluído");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        br.pro.GestaoFinanceira.extras.Formularios.tratarCampos(this, true);
        jbSalvar.setEnabled(true);
        jbSalvar1.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbCancelar1.setEnabled(true);
        jbNovo.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbEditar.setEnabled(false);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        try {
            DefaultTableModel mp = (DefaultTableModel)jtbDados.getModel();
            lista = DAO.pesquisar(jtPesquisa.getText());
            mp.setNumRows(0);
            for(ClienteModel ob: lista){
                mp.addRow(new String[]{""+ob.getIdcliente(),ob.getNomecliente(),ob.getCpfcliente(),ob.getDatanasccliente()});
            }
            jbCancelar1.setEnabled(true);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+e.getMessage());
        }
    }//GEN-LAST:event_jtPesquisaKeyReleased

    private void jtbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDadosMouseClicked
        try {
            int linha = jtbDados.getSelectedRow();
            if(linha>-1){
                jlIdcliente1.setText(jtbDados.getValueAt(linha, 0).toString());
                jtDatanasccliente1.setText(jtbDados.getValueAt(linha, 3).toString());
                jtCidadecliente1.setText(""+lista.get(linha).getCidadecliente());
                jtNumcasacliente1.setText(""+lista.get(linha).getNumcasacliente());
                jtComplcasacliente1.setText(""+lista.get(linha).getComplcliente());
                jtContatocliente1.setText(""+lista.get(linha).getContatocliente());
                jtNomecliente1.setText(jtbDados.getValueAt(linha, 1).toString());
                jtCpfcliente1.setText(jtbDados.getValueAt(linha, 2).toString());
                jtEmailcliente1.setText(""+lista.get(linha).getEmailcliente());
                jtRuacliente1.setText(""+lista.get(linha).getRuacliente());
                for(int i=0;i<listaEmpresa.size();i++){
                    if(listaEmpresa.get(i).getIdempresa() == lista.get(linha).getEmpresa().getIdempresa()){
                        jcbEmpresa.setSelectedIndex(i);
                    }
                }
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jbCancelar1.setEnabled(true);
            } else {
                jbEditar.setEnabled(false);
                jbExcluir.setEnabled(false);
                jbCancelar1.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar o registro: "+e.getMessage());
        }
    }//GEN-LAST:event_jtbDadosMouseClicked

    private void jtDatanascclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDatanascclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDatanascclienteActionPerformed

    private void jtComplcasaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtComplcasaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtComplcasaclienteActionPerformed

    private void jtNumcasaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumcasaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumcasaclienteActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        br.pro.GestaoFinanceira.extras.Formularios.limparCampos(this);
        br.pro.GestaoFinanceira.extras.Formularios.tratarCampos(this, false);
        br.pro.GestaoFinanceira.extras.Formularios.limparTabela(jtbDados);
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbSalvar1.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbCancelar1.setEnabled(false);
        jbEditar.setEnabled(true);
        jbExcluir.setEnabled(false);
        jtPesquisa.setText("");
        jtPesquisa.setEnabled(true);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjeto()){
                    if(DAO.incluir(obj)){
                        JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso", "Salvar", JOptionPane.WARNING_MESSAGE);
                        jbCancelarActionPerformed(evt);
                    }else{
                        JOptionPane.showMessageDialog(this, "Erro ao salvar: ", "Salvar-Cliente", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Salvar-Cliente", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        br.pro.GestaoFinanceira.extras.Formularios.limparCampos(this);
        br.pro.GestaoFinanceira.extras.Formularios.tratarCampos(this, true);
        br.pro.GestaoFinanceira.extras.Formularios.limparTabela(jtbDados);
        jlIdcliente1.setText("0");
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbSalvar1.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbCancelar1.setEnabled(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jtCpfclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCpfclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCpfclienteActionPerformed

    private void jtEmailclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailclienteActionPerformed

    private void jtRuaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRuaclienteActionPerformed

    private void jtCidadeclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadeclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadeclienteActionPerformed

    private void jtNomeclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeclienteActionPerformed

    private void jtContatoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtContatoclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtContatoclienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelar1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbSalvar1;
    private javax.swing.JComboBox<String> jcbEmpresa;
    private javax.swing.JLabel jlCidadecliente;
    private javax.swing.JLabel jlCidadecliente1;
    private javax.swing.JLabel jlComplcasacliente;
    private javax.swing.JLabel jlComplcasacliente1;
    private javax.swing.JLabel jlContatoCliente1;
    private javax.swing.JLabel jlContatocliente;
    private javax.swing.JLabel jlCpfcliente;
    private javax.swing.JLabel jlCpfcliente1;
    private javax.swing.JLabel jlDadospessoais;
    private javax.swing.JLabel jlDatanasccliente;
    private javax.swing.JLabel jlDatanasccliente1;
    private javax.swing.JLabel jlEmailcliente;
    private javax.swing.JLabel jlEmailcliente1;
    private javax.swing.JLabel jlEmpresa;
    private javax.swing.JLabel jlIdcliente;
    private javax.swing.JLabel jlIdcliente1;
    private javax.swing.JLabel jlLocalizacao;
    private javax.swing.JLabel jlNomecliente;
    private javax.swing.JLabel jlNomecliente1;
    private javax.swing.JLabel jlNumcasacliente;
    private javax.swing.JLabel jlNumcasacliente1;
    private javax.swing.JLabel jlPesquisa;
    private javax.swing.JLabel jlRuacliente;
    private javax.swing.JLabel jlRuacliente1;
    private javax.swing.JTextField jtCidadecliente;
    private javax.swing.JTextField jtCidadecliente1;
    private javax.swing.JTextField jtComplcasacliente;
    private javax.swing.JTextField jtComplcasacliente1;
    private javax.swing.JTextField jtContatocliente;
    private javax.swing.JTextField jtContatocliente1;
    private javax.swing.JTextField jtCpfcliente;
    private javax.swing.JTextField jtCpfcliente1;
    private javax.swing.JTextField jtDatanasccliente;
    private javax.swing.JTextField jtDatanasccliente1;
    private javax.swing.JTextField jtEmailcliente;
    private javax.swing.JTextField jtEmailcliente1;
    private javax.swing.JTextField jtNomecliente;
    private javax.swing.JTextField jtNomecliente1;
    private javax.swing.JTextField jtNumcasacliente;
    private javax.swing.JTextField jtNumcasacliente1;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTextField jtRuacliente;
    private javax.swing.JTextField jtRuacliente1;
    private javax.swing.JTable jtbDados;
    // End of variables declaration//GEN-END:variables
public boolean validarCampos() throws Exception{
    return true;
}
public boolean preencherObjeto() throws Exception{
    obj.setIdcliente(Integer.parseInt(jlIdcliente1.getText()));
    obj.setNomecliente(jtNomecliente.getText());
    obj.setCpfcliente(jtCpfcliente.getText());
    obj.setDatanasccliente(jtDatanasccliente.getText());
    obj.setEmailcliente(jtEmailcliente.getText());
    obj.setRuacliente(jtRuacliente.getText());
    obj.setCidadecliente(jtCidadecliente.getText());
    obj.setNumcasacliente(jtNumcasacliente.getText());
    obj.setComplcliente(jtComplcasacliente.getText());
    obj.setContatocliente(jtContatocliente.getText());
    obj.setEmpresa(listaEmpresa.get(jcbEmpresa.getSelectedIndex()));
    return true;
}
public boolean atualizarObjeto() throws Exception{
    obj.setIdcliente(Integer.parseInt(jlIdcliente1.getText()));
    obj.setNomecliente(jtNomecliente1.getText());
    obj.setCpfcliente(jtCpfcliente1.getText());
    obj.setDatanasccliente(jtDatanasccliente1.getText());
    obj.setEmailcliente(jtEmailcliente1.getText());
    obj.setRuacliente(jtRuacliente1.getText());
    obj.setCidadecliente(jtCidadecliente1.getText());
    obj.setNumcasacliente(jtNumcasacliente1.getText());
    obj.setComplcliente(jtComplcasacliente1.getText());
    obj.setContatocliente(jtContatocliente1.getText());
    obj.setEmpresa(listaEmpresa.get(jcbEmpresa.getSelectedIndex()));
    return true;
}
}
