/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pro.GestaoFinanceira.view;

import br.pro.GestaoFinanceira.data.EmpresaData;
import br.pro.GestaoFinanceira.model.EmpresaModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author heito
 */
public class JIFCadEmpresa extends javax.swing.JInternalFrame {
    
    ArrayList<EmpresaModel> lista;
    EmpresaModel obj;
    EmpresaData DAO;
    //int acao=0;
    /**
     * Creates new form JIFCadFuncionario
     */
    public JIFCadEmpresa() {
        
        try{
            lista = new ArrayList<>();            
            obj = new EmpresaModel();
            DAO = new EmpresaData();
            initComponents();
            formatarCampos();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro"+e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpEdicao = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlIdempresa = new javax.swing.JLabel();
        jlContatoempresa = new javax.swing.JLabel();
        jlNomeempresa = new javax.swing.JLabel();
        jtNomeempresa = new javax.swing.JTextField();
        jlCidadeempresa = new javax.swing.JLabel();
        jtCidadeempresa = new javax.swing.JTextField();
        jlIdempresa1 = new javax.swing.JLabel();
        jlRuaempresa = new javax.swing.JLabel();
        jtRuaempresa = new javax.swing.JTextField();
        jtEmailempresa = new javax.swing.JTextField();
        jlEmailempresa = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jlNumempresa = new javax.swing.JLabel();
        jtNumempresa = new javax.swing.JTextField();
        jlDadospessoais = new javax.swing.JLabel();
        jlLocalizacao = new javax.swing.JLabel();
        jtContatoempresa = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDados = new javax.swing.JTable();
        jlPesquisa = new javax.swing.JLabel();
        jtPesquisa = new javax.swing.JTextField();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbSalvar1 = new javax.swing.JButton();
        jlNomeempresa1 = new javax.swing.JLabel();
        jtNomeempresa1 = new javax.swing.JTextField();
        jtEmailempresa1 = new javax.swing.JTextField();
        jlEmailempresa1 = new javax.swing.JLabel();
        jlCidadeempresa1 = new javax.swing.JLabel();
        jtCidadeempresa1 = new javax.swing.JTextField();
        jlRuaempresa1 = new javax.swing.JLabel();
        jtRuaempresa1 = new javax.swing.JTextField();
        jlNumempresa1 = new javax.swing.JLabel();
        jtNumempresa1 = new javax.swing.JTextField();
        jlContatoempresa1 = new javax.swing.JLabel();
        jbCancelar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbPesquisar = new javax.swing.JButton();
        jtContatoempresa1 = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro/Edição de Empresas");
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(1057, 650));

        jPanel1.setLayout(null);

        jlIdempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIdempresa.setText("*ID:");
        jPanel1.add(jlIdempresa);
        jlIdempresa.setBounds(10, 62, 100, 30);

        jlContatoempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlContatoempresa.setText("Telefone:");
        jPanel1.add(jlContatoempresa);
        jlContatoempresa.setBounds(10, 492, 100, 30);

        jlNomeempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNomeempresa.setText("*Nome:");
        jPanel1.add(jlNomeempresa);
        jlNomeempresa.setBounds(10, 110, 100, 30);

        jtNomeempresa.setEnabled(false);
        jtNomeempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeempresaActionPerformed(evt);
            }
        });
        jPanel1.add(jtNomeempresa);
        jtNomeempresa.setBounds(114, 110, 237, 30);

        jlCidadeempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCidadeempresa.setText("Cidade Atual:");
        jPanel1.add(jlCidadeempresa);
        jlCidadeempresa.setBounds(10, 348, 100, 30);

        jtCidadeempresa.setEnabled(false);
        jtCidadeempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadeempresaActionPerformed(evt);
            }
        });
        jPanel1.add(jtCidadeempresa);
        jtCidadeempresa.setBounds(114, 348, 237, 30);

        jlIdempresa1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlIdempresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIdempresa1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jlIdempresa1);
        jlIdempresa1.setBounds(116, 62, 237, 30);

        jlRuaempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRuaempresa.setText("Rua/AV:");
        jPanel1.add(jlRuaempresa);
        jlRuaempresa.setBounds(10, 396, 100, 30);

        jtRuaempresa.setEnabled(false);
        jtRuaempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuaempresaActionPerformed(evt);
            }
        });
        jPanel1.add(jtRuaempresa);
        jtRuaempresa.setBounds(114, 396, 237, 30);

        jtEmailempresa.setEnabled(false);
        jtEmailempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailempresaActionPerformed(evt);
            }
        });
        jPanel1.add(jtEmailempresa);
        jtEmailempresa.setBounds(114, 158, 237, 30);

        jlEmailempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEmailempresa.setText("*Email:");
        jPanel1.add(jlEmailempresa);
        jlEmailempresa.setBounds(10, 158, 100, 30);

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbNovoIcon.png"))); // NOI18N
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jbNovo);
        jbNovo.setBounds(10, 206, 50, 40);

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbSalvarIcon.png"))); // NOI18N
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalvar);
        jbSalvar.setBounds(130, 206, 50, 40);

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbCancelarIcon.png"))); // NOI18N
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar);
        jbCancelar.setBounds(70, 206, 50, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 275, 470, 10);

        jlNumempresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNumempresa.setText("Número da Casa:");
        jPanel1.add(jlNumempresa);
        jlNumempresa.setBounds(10, 444, 100, 30);

        jtNumempresa.setEnabled(false);
        jtNumempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumempresaActionPerformed(evt);
            }
        });
        jPanel1.add(jtNumempresa);
        jtNumempresa.setBounds(114, 444, 237, 30);

        jlDadospessoais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlDadospessoais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDadospessoais.setText("CADASTRO EMPRESA");
        jPanel1.add(jlDadospessoais);
        jlDadospessoais.setBounds(0, 11, 1016, 33);

        jlLocalizacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlLocalizacao.setText("ENDEREÇO");
        jPanel1.add(jlLocalizacao);
        jlLocalizacao.setBounds(0, 288, 1016, 33);

        jtContatoempresa.setEnabled(false);
        jPanel1.add(jtContatoempresa);
        jtContatoempresa.setBounds(114, 492, 237, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/JIFCadEmpresaIcon.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 40, 520, 520);

        jtpEdicao.addTab("Cadastro", jPanel1);

        jtbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDados);

        jlPesquisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPesquisa.setText("Pesquisar:");

        jtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisaKeyReleased(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbEditarIcon.png"))); // NOI18N
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbExcluirIcon.png"))); // NOI18N
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbSalvarIcon.png"))); // NOI18N
        jbSalvar1.setEnabled(false);
        jbSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvar1ActionPerformed(evt);
            }
        });

        jlNomeempresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNomeempresa1.setText("*Nome:");

        jtNomeempresa1.setEnabled(false);
        jtNomeempresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeempresa1ActionPerformed(evt);
            }
        });

        jtEmailempresa1.setEnabled(false);
        jtEmailempresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailempresa1ActionPerformed(evt);
            }
        });

        jlEmailempresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEmailempresa1.setText("*Email:");

        jlCidadeempresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCidadeempresa1.setText("Cidade:");

        jtCidadeempresa1.setEnabled(false);
        jtCidadeempresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadeempresa1ActionPerformed(evt);
            }
        });

        jlRuaempresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRuaempresa1.setText("Rua:");

        jtRuaempresa1.setEnabled(false);
        jtRuaempresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuaempresa1ActionPerformed(evt);
            }
        });

        jlNumempresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNumempresa1.setText("Número:");

        jtNumempresa1.setEnabled(false);
        jtNumempresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumempresa1ActionPerformed(evt);
            }
        });

        jlContatoempresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlContatoempresa1.setText("Telefone:");

        jbCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbCancelarIcon.png"))); // NOI18N
        jbCancelar1.setEnabled(false);
        jbCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pesquise o nome para realizar Alteração/Exclusão de EMPRESAS");

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/pro/GestaoEmpresarial/Icon/jbPesquisaIcon.png"))); // NOI18N
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jtContatoempresa1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlContatoempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtContatoempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlNomeempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNomeempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlEmailempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEmailempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 196, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlRuaempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtRuaempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlCidadeempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCidadeempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlNumempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNumempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 379, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCidadeempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCidadeempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRuaempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRuaempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNumempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNumempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNomeempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNomeempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtEmailempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEmailempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlContatoempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtContatoempresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpEdicao.addTab("Edição", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpEdicao)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpEdicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar1ActionPerformed
        br.pro.GestaoFinanceira.extras.Formularios.limparCampos(this);
        br.pro.GestaoFinanceira.extras.Formularios.tratarCampos(this, false);
        br.pro.GestaoFinanceira.extras.Formularios.limparTabela(jtbDados);
        jbSalvar1.setEnabled(false);
        jbCancelar1.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jtPesquisa.setText("");
        jtPesquisa.setEnabled(true);
        jbPesquisar.setEnabled(true);
        jtpEdicao.setEnabled(true);
    }//GEN-LAST:event_jbCancelar1ActionPerformed

    private void jtNumempresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumempresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumempresa1ActionPerformed

    private void jtRuaempresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuaempresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRuaempresa1ActionPerformed

    private void jtCidadeempresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadeempresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadeempresa1ActionPerformed

    private void jtEmailempresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailempresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailempresa1ActionPerformed

    private void jtNomeempresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeempresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeempresa1ActionPerformed

    private void jbSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvar1ActionPerformed
        try{
            if(validarCampos1()){
                if(atualizarObjeto()){
                    if(DAO.editar(obj)){
                        JOptionPane.showMessageDialog(rootPane, "Atualizado com sucesso", "Atualizar", JOptionPane.WARNING_MESSAGE);
                        jbCancelar1ActionPerformed(evt);
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Erro ao Atualizar: ", "Atualizar-Empresa", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), "Atualizar-Empresa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvar1ActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this ,"Você tem certeza que deseja Excluir a Empresa ("+jtNomeempresa.getText()+")", "Exclusão",JOptionPane.YES_NO_OPTION);
        if (resposta == 0) {
            try {
                if(DAO.excluir(Integer.parseInt(jlIdempresa1.getText()))){
                    JOptionPane.showMessageDialog(this, "Excluído com sucesso");
                    jbCancelar1ActionPerformed(evt);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o registro: "+e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "O registro não será excluído");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        br.pro.GestaoFinanceira.extras.Formularios.tratarCampos(this, true);
        jbSalvar1.setEnabled(true);
        jbCancelar1.setEnabled(true);
        jbExcluir.setEnabled(false);
        jbEditar.setEnabled(false);
        jbPesquisar.setEnabled(false);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisaKeyReleased
        
    }//GEN-LAST:event_jtPesquisaKeyReleased

    private void jtbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDadosMouseClicked
        try {
            int linha = jtbDados.getSelectedRow();
            if(linha>-1){
                jlIdempresa1.setText(jtbDados.getValueAt(linha, 0).toString());
                jtNomeempresa1.setText(jtbDados.getValueAt(linha, 1).toString());
                jtNumempresa1.setText(""+lista.get(linha).getNumempresa());
                jtContatoempresa1.setText(""+lista.get(linha).getContatoempresa());
                jtEmailempresa1.setText(jtbDados.getValueAt(linha, 2).toString());
                jtCidadeempresa1.setText(""+lista.get(linha).getCidadeempresa());
                jtRuaempresa1.setText(""+lista.get(linha).getRuaempresa());
                jbEditar.setEnabled(true);
                jbExcluir.setEnabled(true);
                jbCancelar1.setEnabled(true);
                jbPesquisar.setEnabled(false);
                jtpEdicao.setEnabled(false);
            } else {
                jbEditar.setEnabled(false);
                jbExcluir.setEnabled(false);
                jbCancelar1.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar o registro: "+e.getMessage());
        }
    }//GEN-LAST:event_jtbDadosMouseClicked

    private void jtNumempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumempresaActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        br.pro.GestaoFinanceira.extras.Formularios.limparCampos(this);
        br.pro.GestaoFinanceira.extras.Formularios.tratarCampos(this, false);
        br.pro.GestaoFinanceira.extras.Formularios.limparTabela(jtbDados);
        jbNovo.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbCancelar.setEnabled(false);
        jtPesquisa.setEnabled(true);
        jbPesquisar.setEnabled(true);
        jtpEdicao.setEnabled(true);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjeto()){
                    if(DAO.incluir(obj)){
                        JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso", "Salvar", JOptionPane.WARNING_MESSAGE);
                        jbCancelarActionPerformed(evt);
                    }else{
                        JOptionPane.showMessageDialog(this, "Erro ao salvar: ", "Salvar-Empresa", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Salvar-Empresa", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        br.pro.GestaoFinanceira.extras.Formularios.limparCampos(this);
        br.pro.GestaoFinanceira.extras.Formularios.tratarCampos(this, true);
        br.pro.GestaoFinanceira.extras.Formularios.limparTabela(jtbDados);
        jlIdempresa1.setText("0");
        jbNovo.setEnabled(false);
        jbSalvar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jtpEdicao.setEnabled(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jtEmailempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailempresaActionPerformed

    private void jtRuaempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuaempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRuaempresaActionPerformed

    private void jtCidadeempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadeempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCidadeempresaActionPerformed

    private void jtNomeempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeempresaActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        try {
            DefaultTableModel mp = (DefaultTableModel)jtbDados.getModel();
            lista = DAO.pesquisar(jtPesquisa.getText());
            mp.setNumRows(0);
            for(EmpresaModel ob: lista){
                mp.addRow(new String[]{""+ob.getIdempresa(),ob.getNomeempresa(),ob.getEmailempresa()});
            }
            jbCancelar1.setEnabled(true);
            jbPesquisar.setEnabled(false);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro: "+e.getMessage());
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelar1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbSalvar1;
    private javax.swing.JLabel jlCidadeempresa;
    private javax.swing.JLabel jlCidadeempresa1;
    private javax.swing.JLabel jlContatoempresa;
    private javax.swing.JLabel jlContatoempresa1;
    private javax.swing.JLabel jlDadospessoais;
    private javax.swing.JLabel jlEmailempresa;
    private javax.swing.JLabel jlEmailempresa1;
    private javax.swing.JLabel jlIdempresa;
    private javax.swing.JLabel jlIdempresa1;
    private javax.swing.JLabel jlLocalizacao;
    private javax.swing.JLabel jlNomeempresa;
    private javax.swing.JLabel jlNomeempresa1;
    private javax.swing.JLabel jlNumempresa;
    private javax.swing.JLabel jlNumempresa1;
    private javax.swing.JLabel jlPesquisa;
    private javax.swing.JLabel jlRuaempresa;
    private javax.swing.JLabel jlRuaempresa1;
    private javax.swing.JTextField jtCidadeempresa;
    private javax.swing.JTextField jtCidadeempresa1;
    private javax.swing.JFormattedTextField jtContatoempresa;
    private javax.swing.JFormattedTextField jtContatoempresa1;
    private javax.swing.JTextField jtEmailempresa;
    private javax.swing.JTextField jtEmailempresa1;
    private javax.swing.JTextField jtNomeempresa;
    private javax.swing.JTextField jtNomeempresa1;
    private javax.swing.JTextField jtNumempresa;
    private javax.swing.JTextField jtNumempresa1;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTextField jtRuaempresa;
    private javax.swing.JTextField jtRuaempresa1;
    private javax.swing.JTable jtbDados;
    private javax.swing.JTabbedPane jtpEdicao;
    // End of variables declaration//GEN-END:variables
private boolean validarCampos() throws Exception{
    if(jtNomeempresa.getText().equals("") ){
        JOptionPane.showMessageDialog(null, "Nome Empresa Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if(jtEmailempresa.getText().equals("") ){
        JOptionPane.showMessageDialog(null, "Email Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
}
private boolean validarCampos1(){
     if(jtNomeempresa1.getText().equals("") ){
        JOptionPane.showMessageDialog(null, "Nome Empresa Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if(jtEmailempresa1.getText().equals("") ){
        JOptionPane.showMessageDialog(null, "Email Vazio", "ERRO", JOptionPane.ERROR_MESSAGE);
        return false;
    } 
    return true;
}
private boolean preencherObjeto() throws Exception{
    obj.setIdempresa(Integer.parseInt(jlIdempresa1.getText()));
    obj.setNomeempresa(jtNomeempresa.getText());
    obj.setEmailempresa(jtEmailempresa.getText());
    obj.setRuaempresa(jtRuaempresa.getText());
    obj.setCidadeempresa(jtCidadeempresa.getText());
    obj.setNumempresa(jtNumempresa.getText());
    obj.setContatoempresa(jtContatoempresa.getText());
    return true;
}
private boolean atualizarObjeto() throws Exception{
    obj.setIdempresa(Integer.parseInt(jlIdempresa1.getText()));
    obj.setNomeempresa(jtNomeempresa1.getText());
    obj.setEmailempresa(jtEmailempresa1.getText());
    obj.setRuaempresa(jtRuaempresa1.getText());
    obj.setCidadeempresa(jtCidadeempresa1.getText());
    obj.setNumempresa(jtNumempresa1.getText());
    obj.setContatoempresa(jtContatoempresa1.getText());
    return true;
}
private void formatarCampos() throws Exception{
        MaskFormatter maskcontato = new MaskFormatter("(+55)(###)#########");
        maskcontato.install(jtContatoempresa);
        maskcontato.install(jtContatoempresa1);
    }

}
